### Test  GET / Request
GET  http://localhost:8383

### Test GET / Dashboard
GET  http://localhost:8383/dashboard

### Data Endpoint
GET  http://localhost:8383/api/data

### Test POST /api/data
POST http://localhost:8383/api/data
Content-Type: application/json

{
    "name": "Kipngetich Ngeno",
    "age": 30,
    "occupation": "Electrical Engineer"
}

### Delete Endpoint
DELETE http://localhost:8383/api/data
