services:
  main_project2:
    image: main_project2
    build:
      context: main_project2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5003:5003
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
