### Get /
GET http://localhost:5003

###
# Post request endpoint to register a new user on auth/register
# The request body should contain the username and password in JSON format
# The response will contain a success message or an error message
POST http://localhost:5003/auth/register
Content-Type: application/json


{
    "username": "gilgamesh@gmail.com",
    "password": "12345678"
}

###
# Post request endpoint to login a user on auth/login
# The request body should contain the username and password in JSON format
# The response will contain a success message or an error message
# If the login is successful, it will return a token that can be used for subsequent requests
# The token should be included in the Authorization header for protected routes
POST http://localhost:5003/auth/login
Content-Type: application/json


{
    "username": "gilgamesh@gmail.com",
    "password": "12345678"
}


### Fetch all todos for the authenticated user
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxMzYyMTA4LCJleHAiOjE3NTE0NDg1MDh9.HDbN48llMzepm-nfKikre8PBlXqQQgikYQGKzI6cMEU


### Post a new todo for the authenticated user
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxMzYyMTA4LCJleHAiOjE3NTE0NDg1MDh9.HDbN48llMzepm-nfKikre8PBlXqQQgikYQGKzI6cMEU
Content-Type: application/json

{
    "task": "Complete the project documentation"
}

### Update a todo for the authenticated user(protected authorization)
PUT http://localhost:5003/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxMzYyMTA4LCJleHAiOjE3NTE0NDg1MDh9.HDbN48llMzepm-nfKikre8PBlXqQQgikYQGKzI6cMEU
Content-Type: application/json

{
    "task": "Complete the project documentation and review",
    "completed": 1
}