services:
  app:
    build: .
    container_name: todo_app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todoapp
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=5003
    ports:
      - "5003:5003"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoapp
    ports:
      - "5433:5432"  # Changed to avoid local conflict
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: